### ISSUE TITLE
Soportar recibir imágenes y subirlas a Cloudinary

### ISSUE THREAD

**Issue by leo10099** [proyectopop/alberto_chatbot_backend#3]
- [x] Levantar una ruta para recibir imágenes con [Multer](https://github.com/expressjs/multer).

- [x] - Integrar [librería](https://github.com/cloudinary/cloudinary_npm) Node JS de Cloudinary

- [x] - Normalizar las imágenes a 300px de máximo de ancho

- [x] - El método debe retornar como string la URI de la imágen subida a Cloudinary

**Comment by joelmatiassilva** [comment]
@leo10099 que  significa normalizar? a toda imagen que supera los 300px, tiene que estar a 300px?

**Comment by leo10099** [comment]
@joelmatiassilva Si. Cloudinary te auto ajusta el alto automaticamente. 

`cloudinary.image("sample.jpg", {width: 300, crop: "scale"})`
